### ISSUE TITLE
Add `tools.DateTime`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape-tools#18]
LLMs often need to retrieve current date and time. We can build a tool for that.

**Comment by GambetaClub** [comment]
Hi Vasinov,

I suggest closing this issue since the tool was already implemented on commit [#8220ac6](https://github.com/griptape-ai/griptape-tools/commit/8220ac68fd963adef052dbfc473da579217be0c4)

By the way, I am trying to work on some good first issues. Let me know if you have any in mind. 

Best regards,
Mariano
